# Generated by Django 5.1.2 on 2025-01-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollows",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userfollows",
            name="followed_user",
        ),
        migrations.RemoveField(
            model_name="userfollows",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserBlocks",
        ),
        migrations.DeleteModel(
            name="UserFollows",
        ),
    ]
