# Generated by Django 5.1.2 on 2024-12-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
