# Generated by Django 5.1.2 on 2024-12-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0003_alter_ticket_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True,
                default="ticket_images/livre-apprendre-python-debutants-top5",
                null=True,
                upload_to="ticket_images/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
