# Generated by Django 5.1.2 on 2024-12-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0004_alter_ticket_image_alter_ticket_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="slug",
            field=models.SlugField(
                blank=True, default="vide", max_length=256, unique=True
            ),
            preserve_default=False,
        ),
    ]
