# Generated by Django 5.1.2 on 2024-12-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0008_alter_review_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="slug",
            new_name="review_slug",
        ),
    ]
