# Generated by Django 5.1.2 on 2024-12-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0010_alter_review_review_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review_slug",
            new_name="slug",
        ),
    ]
