# Generated by Django 5.1.2 on 2025-01-16 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0011_rename_review_slug_review_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-time_created"], "verbose_name": "Livre ou Article"},
        ),
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(
                blank=True, max_length=8192, verbose_name="Commentaires "
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="headline",
            field=models.CharField(
                max_length=128, verbose_name="En-tête de la critique"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "☆☆☆☆☆"),
                    (1, "★☆☆☆☆"),
                    (2, "★★☆☆☆"),
                    (3, "★★★☆☆"),
                    (4, "★★★★☆"),
                    (5, "★★★★★"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Note sur 5 étoiles",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création de la critique"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=2048,
                verbose_name="Description du livre ou de l'article",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True,
                default="ticket_images/livre-apprendre-python-debutants-top5.jpg",
                null=True,
                upload_to="ticket_images/",
                verbose_name="Image du livre ou de l'article",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name="Date de création du livre ou de l'article",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(
                max_length=128, verbose_name="Nom du livre ou de l'article"
            ),
        ),
    ]
