# Generated by Django 5.1.2 on 2025-01-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0012_alter_ticket_options_alter_review_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True,
                default="ticket_images/livre-apprendre-python-debutants-top5.jpg",
                help_text="Ajoutez une image du livre ou de l'article",
                null=True,
                upload_to="ticket_images/",
                verbose_name="Image du livre ou de l'article",
            ),
        ),
    ]
