# Generated by Django 5.1.2 on 2025-01-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0013_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Ajoutez une image du livre ou de l'article",
                null=True,
                upload_to="ticket_images/",
                verbose_name="Image du livre ou de l'article",
            ),
        ),
    ]
