# Generated by Django 5.1.2 on 2025-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0015_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de publication de la critique"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True,
                default="ticket_images/django.png",
                null=True,
                upload_to="ticket_images/",
                verbose_name="Image du livre/article",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name="Date de la demande de la critique sur un livre/article",
            ),
        ),
    ]
