# Generated by Django 5.1.2 on 2025-03-06 20:52

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0016_alter_review_time_created_alter_ticket_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="rien",
                editable=False,
                max_length=256,
                populate_from="title",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
