# Generated by Django 5.1.2 on 2025-03-06 21:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0017_alter_ticket_slug_alter_ticket_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="rien",
                editable=False,
                max_length=256,
                populate_from="headline",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
