# Generated by Django 5.1.2 on 2025-01-31 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("followup", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserBlocks",
            new_name="UserBlock",
        ),
        migrations.RenameModel(
            old_name="UserFollows",
            new_name="UserFollow",
        ),
    ]
